packages:
  - docs

overrides:
  '@shikijs/core': ^4.4.3
  '@shikijs/transformers': ^4.4.3
  '@shikijs/types': ^4.4.3
  '@shikijs/vitepress-twoslash': ^4.4.3
  esbuild: ^0.28.2

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAge: 0
