packages:
  - docs

overrides:
  '@shikijs/core': ^4.3.1
  '@shikijs/transformers': ^4.3.1
  '@shikijs/types': ^4.3.1
  '@shikijs/vitepress-twoslash': ^4.3.1
  esbuild: ^0.28.1

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAge: 0
